# ==> Create JDK directories
- name: Create tmp directory
  file: state=directory path='{{ tmp_dir }}' owner={{ oracle_user }} group={{ oracle_group }}

- name: Create java home directory
  delegate_to: "{{ hostvars[groups['wl_admin'][0]]['ansible_ssh_host'] }}"
  file: state=directory path={{ java_home }} owner={{ oracle_user }} group={{ oracle_group }}

# ==> Copy JDK archive
- name: Copy jdk archive
  copy: src={{ jdk_installer_archive }} dest={{ tmp_dir }}/{{ jdk_installer_archive }}
  args:
    force: no
  when: inventory_hostname in groups['wl_admin']

# ==> Extract JDK archive
- name: Extract jdk archive
  unarchive:
    src: '{{ tmp_dir }}/{{ jdk_installer_archive }}'
    dest: '{{ java_home }}'
    remote_src: yes
    owner: '{{ oracle_user }}'
    group: '{{ oracle_group }}'
    extra_opts:
      - --strip-components=1
  when: inventory_hostname in groups['wl_admin']

# ==> JVM delay fix
- name: Set securerandom.source to '/dev/urandom'
  replace:
    path: '{{ java_home }}/jre/lib/security/java.security'
    regexp: '^securerandom.source=file:/dev/random'
    replace: 'securerandom.source=file:/dev/urandom'
  when: inventory_hostname in groups['wl_admin']

# ==> Java environment variables
- name: Add JAVA_HOME environment variariables in .bashrc
  lineinfile: dest='/home/{{ oracle_user }}/.bashrc' line='export JAVA_HOME={{ java_home }}'

- name: Add JAVA_HOME to PATH in .bashrc
  lineinfile: dest='/home/{{ oracle_user }}/.bashrc' line='export PATH=$PATH:$JAVA_HOME/bin'