---
- name: OS check
  hosts: all
  become: true
  tasks:
    - debug:
        msg:
          - "os_family: {{ ansible_os_family }}"
          - "distribution: {{ ansible_distribution }}"
          - "major_version: {{ ansible_distribution_major_version }}"