# ==> Set hostname
- name: Setting hostnames
  hostname: name={{ inventory_hostname }}

# ==> Create user and groups
- name: Create group 'oinstall' with specific gid
  group: name={{ oracle_group }} gid={{ oracle_group_id }}

- name: Create user 'oracle' with specific uid and a primary group of 'oinstall'
  user: name={{ oracle_user }} uid={{ oracle_user_id }} group={{ oracle_group }}

# ==> Create Base Directories
- name: Create weblogic base directory
  delegate_to: "{{ hostvars[groups['wl_admin'][0]]['ansible_ssh_host'] }}"
  file: state=directory path={{ oracle_base }} owner={{ oracle_user }} group={{ oracle_group }}

- name: Create oracle home directory
  delegate_to: "{{ hostvars[groups['wl_admin'][0]]['ansible_ssh_host'] }}"
  file: state=directory path={{ oracle_home }} owner={{ oracle_user }} group={{ oracle_group }}

- name: Create domain home directory
  delegate_to: "{{ hostvars[groups['wl_admin'][0]]['ansible_ssh_host'] }}"
  file: state=directory path={{ domain_home }} owner={{ oracle_user }} group={{ oracle_group }}

# ==> Create tmp directories
# - name: Create tmp directory
#   file: state=directory path='{{ tmp_dir }}' owner={{ oracle_user }} group={{ oracle_group }}